--Ex1:
select Name from city
where population > 120000
and countrycode = 'USA'
--Ex2:
select * from City
where countrycode = 'JPN'
--Ex3:
select CITY, STATE from STATION;
--Ex4:
select distinct CITY FROM STATION
WHERE CITY LIKE  'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%'
--EX5: 
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%A'
OR CITY LIKE '%E'
OR CITY LIKE '%I'
OR CITY LIKE '%O'
OR CITY LIKE '%U'
--EX6:
SELECT DISTINCT CITY FROM STATION 
WHERE NOT
(CITY LIKE 'A%'
OR CITY LIKE 'E%'
OR CITY LIKE 'U%'
OR CITY LIKE 'O%'
OR CITY LIKE 'I%')
--EX7:
SELECT NAME FROM EMPLOYEE
ORDER BY NAME 
--EX8:
SELECT NAME FROM EMPLOYEE
WHERE SALARY > 2000
AND MONTHS < 10
ORDER BY EMPLOYEE_ID
--EX9:
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS = 'Y'
AND RECYCLABLE = 'Y'
--Ex10:
SELECT NAME FROM CUSTOMER
WHERE REFEREE_ID != 2
Or REFEREE_ID is null
--EX11: 
SELECT NAME, POPULATION, AREA FROM WORLD
WHERE POPULATION > 25000000
OR AREA > 3000000
--EX12:
SELECT DISTINCT AUTHOR_ID AS id FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY AUTHOR_ID
--EX13: 
SELECT PART FROM parts_assembly
WHERE Finish_date IS NULL
--EX14:
SELECT * FROM lyft_drivers
WHERE yearly_salary < 30000 OR yearly_salary >= 70000
--EX15:
select advertising_channel from uber_advertising
WHERE year = 2019
AND money_spent >= 100000
